# Generated by Django 4.1.1 on 2022-10-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_shopper_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='number',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
