# Generated by Django 4.1.1 on 2022-10-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stors', '0004_alter_cart_ordered_date_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='products'),
            preserve_default=False,
        ),
    ]
