# Generated by Django 4.1.1 on 2023-01-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stors', '0007_alter_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered_date',
        ),
    ]
